//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchPoint
    {
        public int Match_Points_Id { get; set; }
        public int Match_Points { get; set; }
        public int Match_Played_Number { get; set; }
        public int Category_Id { get; set; }
        public int Tournament_Id { get; set; }
        public int Team_Id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Team Team { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
