//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Payment_Id { get; set; }
        public decimal Payment_Amount { get; set; }
        public Nullable<decimal> Outstanding_balance { get; set; }
        public System.DateTime Payment_Date { get; set; }
        public int Client_Admin_Id { get; set; }
        public int Tournament_Id { get; set; }
    
        public virtual Clients_Admin Clients_Admin { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
