//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tournament()
        {
            this.Payments = new HashSet<Payment>();
        }
    
        public int Tournament_Id { get; set; }
        public string Tournament_Name { get; set; }
        public string Tournament_Location { get; set; }
        public int Tournament_Period_Id { get; set; }
        public int Tournament_Type_Id { get; set; }
        public Nullable<int> Playouts_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual Playout Playout { get; set; }
        public virtual Tournaments_Period Tournaments_Period { get; set; }
        public virtual Tournaments_Types Tournaments_Types { get; set; }
    }
}
